use_frameworks!

platform :ios, '9.0'

target 'AnimationComponent_Example' do
  pod 'AnimationComponent', :path => '../'

  target 'AnimationComponent_Tests' do
    inherit! :search_paths

    
  end
end
